# Numpy

In [1]:
#импорт библиотеки numpy
import numpy as np

In [85]:
#создание массива
nd = np.array([[1, 1, 0], [1, 0, 1]])
print(nd)

[[1 1 0]
 [1 0 1]]


In [3]:
x = np.array([i**2 for i in range(5)])
print(x)

[ 0  1  4  9 16]


# Свойства массива

In [86]:
print('Число измерений массива (размерность,ранг) (nd.ndim): ', nd.ndim)
print('Размеры массива (nd.shape): ', nd.shape)
print('Общее количество всех элементов (nd.size): ', nd.size)
print('Тип элемента в массиве (nd.dtype): ', nd.dtype)

#Указываем тип данных при создании
nd1 = np.array([[1, 1, 0], [1, 0, 1]], dtype=np.float32)
print('type nd1 (nd1.dtype): ', nd1.dtype)

#переопределение типов элементов массива в момент создания
print('Изначальный тип элементов массива: ', ([[1.5, 2, 3], [4, 5, 6]]))
print('', )
nd1_ = np.array([[1.5, 2, 3], [4, 5, 6]], dtype=np.complex)
print('Измененный тип элементов массива nd1 (nd1_): ', nd1_)

print('Pазмер одного элемента массива, указанный в байтах (nd.itemsize): ', nd.itemsize)
print('Буфер, содержащий фактические элементы массива(nd1.data): ', nd1.data)
print('Перевод в список из буфера (nd1.data.tolist)', nd1.data.tolist())

Число измерений массива (размерность,ранг) (nd.ndim):  2
Размеры массива (nd.shape):  (2, 3)
Общее количество всех элементов (nd.size):  6
Тип элемента в массиве (nd.dtype):  int32
type nd1 (nd1.dtype):  float32
Изначальный тип элементов массива:  [[1.5, 2, 3], [4, 5, 6]]

Измененный тип элементов массива nd1 (nd1_):  [[1.5+0.j 2. +0.j 3. +0.j]
 [4. +0.j 5. +0.j 6. +0.j]]
Pазмер одного элемента массива, указанный в байтах (nd.itemsize):  4
Буфер, содержащий фактические элементы массива(nd1.data):  <memory at 0x0000022396D6DEA0>
Перевод в список из буфера (nd1.data.tolist) [[1.0, 1.0, 0.0], [1.0, 0.0, 1.0]]


# Изменение формы массива

In [75]:
a = np.array([[[  0,   1,   2], [ 10,  12,  13]], [[100, 101, 102], [110, 112, 113]]])
print('массив а\n', a)
print('посмотреть форму массива\n', a.shape)
print('получить плоский массив\n', a.ravel())  # Делает массив плоским
a.shape = (6, 2)
print('изменить форму\n', a.shape)  # Изменение формы
print('новый массив\n', a)
print('транспонирование\n', a.transpose() ) # Транспонирование
print('изменить форму a.reshape((3, 4)\n', a.reshape((3, 4)))  # Изменение формы
#Порядок элементов в массиве в результате функции ravel() 
#соответствует обычному "C-стилю", то есть, чем правее индекс, тем он "быстрее изменяется": за элементом a[0,0] следует a[0,1]. 
#Если одна форма массива была изменена на другую, массив 
a1=a.reshape((3, 4))
print('a1\n', a1)
print('a1[1]', a1[1])
#в FORTRAN-стиле, в котором быстрее изменяется более левый индекс
a2=a.reshape((3, 4), order='F')
print('a2\n', a2)
print('a2[1]', a2[1])

массив а
 [[[  0   1   2]
  [ 10  12  13]]

 [[100 101 102]
  [110 112 113]]]
посмотреть форму массива
 (2, 2, 3)
получить плоский массив
 [  0   1   2  10  12  13 100 101 102 110 112 113]
изменить форму
 (6, 2)
новый массив
 [[  0   1]
 [  2  10]
 [ 12  13]
 [100 101]
 [102 110]
 [112 113]]
транспонирование
 [[  0   2  12 100 102 112]
 [  1  10  13 101 110 113]]
изменить форму a.reshape((3, 4)
 [[  0   1   2  10]
 [ 12  13 100 101]
 [102 110 112 113]]
a1
 [[  0   1   2  10]
 [ 12  13 100 101]
 [102 110 112 113]]
a1[1] [ 12  13 100 101]
a2
 [[  0 100   1 101]
 [  2 102  10 110]
 [ 12 112  13 113]]
a2[1] [  2 102  10 110]


In [88]:
#Метод reshape() возвращает ее аргумент с измененной формой, 
#в то время как метод resize() изменяет сам массив
a = np.array([[  0,   1], [  2,  10], [ 12,  13], [100, 101], [102, 110], [112, 113]])
g = a.resize((2, 6))
print('Новый а, после g = a.resize((2, 6)\n', a)
#если один из аргументов задается как -1, 
#то он автоматически рассчитывается в соответствии с остальным
j = a.reshape((4, -1))
print('копия а с 4-мя строками и соответстветствующим количеством столбцов\n', j)

Новый а, после g = a.resize((2, 6)
 [[  0   1   2  10  12  13]
 [100 101 102 110 112 113]]
копия а с 4-мя строками и соответстветствующим количеством столбцов
 [[  0   1   2]
 [ 10  12  13]
 [100 101 102]
 [110 112 113]]


# Объединение массивов

In [ ]:
#Несколько массивов могут быть объединены вместе вдоль разных осей 
#с помощью функций hstack и vstack.

#hstack() объединяет массивы по первым осям, vstack() — по последним

In [3]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print('np.vstack \n', np.vstack((a, b)))
print('np.hstack \n', np.hstack((a, b)))

np.vstack 
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
np.hstack 
 [[1 2 5 6]
 [3 4 7 8]]


In [4]:
#функция column_stack() объединяет одномерные массивы в качестве столбцов 
#двумерного массива
np.column_stack((a, b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [5]:
#для строк имеется функция row_stack()
np.row_stack((a, b))


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

# Разбиение массива

In [12]:
#Используя hsplit() вы можете разбить массив вдоль горизонтальной оси, 
#указав либо число возвращаемых массивов одинаковой формы, 
#либо номера столбцов, после которых массив разрезается "ножницами"
a = np.arange(12).reshape((2, 6))
print('первоначальный массив  a\n', a)
p = np.hsplit(a, 3)
print('\nмассив, разбитый на 3 части\n')  # Разбить на 3 части
print('часть первая\n', p[0])
print('часть вторая\n', p[1])
print('часть третья\n', p[2])

первоначальный массив  a
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

массив, разбитый на 3 части

часть первая
 [[0 1]
 [6 7]]
часть вторая
 [[2 3]
 [8 9]]
часть третья
 [[ 4  5]
 [10 11]]


In [14]:
n = np.hsplit(a, (3, 4))  # Разрезать a после третьего и четвёртого столбца
print('первая часть\n', n[0])
print('вторая часть\n', n[1])
print('третья часть\n', n[2])

первая часть
 [[0 1 2]
 [6 7 8]]
вторая часть
 [[3]
 [9]]
третья часть
 [[ 4  5]
 [10 11]]


In [17]:
#Функция vsplit() разбивает массив вдоль вертикальной оси, 
m = np.vsplit(a, 2) 
print('первая часть\n', m[0])
print('вторая часть\n', m[1])

первая часть
 [[0 1 2 3 4 5]]
вторая часть
 [[ 6  7  8  9 10 11]]


In [19]:
#а array_split() позволяет указать оси, вдоль которых произойдет разбиение
g = np.array_split(a, 2, axis=0) 
print('первая часть\n', g[0])
print('вторая часть\n', g[1])

первая часть
 [[0 1 2 3 4 5]]
вторая часть
 [[ 6  7  8  9 10 11]]


In [20]:
f = np.array_split(a, 2, axis=1) 
print('первая часть\n', f[0])
print('вторая часть\n', f[1])

первая часть
 [[0 1 2]
 [6 7 8]]
вторая часть
 [[ 3  4  5]
 [ 9 10 11]]


# Представление или поверхностная копия

In [23]:
#Разные объекты массивов могут использовать одни и те же данные. 
#Метод view() создает новый объект массива, 
#являющийся представлением тех же данных.
a = np.array([1,2,3])
c = a.view()
print('"c is a"', c is a)
print('"c.base is a"', c.base is a)  # c это представление данных, принадлежащих a

"c is a" False
"c.base is a" True


In [24]:
print('"c.flags.owndata"', c.flags.owndata)
print('"a.flags.owndata"', a.flags.owndata)

"c.flags.owndata" False
"a.flags.owndata" True


In [27]:
c.shape = (1,3)
print('c.shape', c.shape)  # форма c поменяется
print('a.shape', a.shape)  # форма а не поменяется

c.shape (1, 3)
a.shape (3,)


In [31]:
#данные меняются (в а) после замены элемента в с
c[0, 1] = 9999
print('a', a, 'c', c)

a [   1 9999    3] c [[   1 9999    3]]


In [34]:
#Срез массива это представление
a = np.array([[1,2,3], [4,5,6]])
s = a[:,1:3]
s[:] = 10
print(s)

[[10 10]
 [10 10]]


# Глубокая копия

In [37]:
#Метод copy() создаст настоящую копию массива и его данных
d = a.copy()  # создается новый объект массива с новыми данными
print(d is a)
print(d.base is a)  # d не имеет ничего общего с а
d[0, 0] = 9999 #после изменения элемента в d - в а ничего не меняется
print(a)

False
False
[[ 1 10 10]
 [ 4 10 10]]


# Инициализация значениями по умолчанию

Можно создать массивы и инициализировать нулями или единицами. Для этого в NumPy существуют две говорящие сами за себя функции zeros() и ones()

In [87]:
nd2 = np.zeros((3, 3))
print(nd2)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [88]:
nd3 = np.ones((3, 3))
print(nd3)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [89]:
#создание единичной матрицы
nd4 = np.eye(3)
print(nd4)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [90]:
#создание матрицы с мусорными значениями
nd5 = np.empty((4,4))
print(nd5)

[[6.23042070e-307 4.67296746e-307 1.69121096e-306 9.34609111e-307]
 [1.11256817e-306 1.06811422e-306 1.42417221e-306 1.11260619e-306]
 [8.90094053e-307 1.86919378e-306 1.06809792e-306 1.37962456e-306]
 [1.69111861e-306 1.78020169e-306 1.37961777e-306 7.56599807e-307]]


In [7]:
#создание матрицы 3 на 2 и заполнение ее элементами -2 с типом int32
x = np.full((3, 2), -2, np.int32)
print(x)

[[-2 -2]
 [-2 -2]
 [-2 -2]]


# Создание массива путем повторения элементов

In [8]:
x = np.array([[1,2,3],[4,5,6]])
y = np.repeat(x,2)
print(y)

[1 1 2 2 3 3 4 4 5 5 6 6]


In [9]:
y = np.repeat(x, 2, axis=0)
print(y)

[[1 2 3]
 [1 2 3]
 [4 5 6]
 [4 5 6]]


In [10]:
y = np.repeat(x, 2, axis=1)
print(y)

[[1 1 2 2 3 3]
 [4 4 5 5 6 6]]


In [13]:
y = np.repeat(x, [2, 0, 5], axis = 1)
print(y)

[[1 1 3 3 3 3 3]
 [4 4 6 6 6 6 6]]


In [15]:
#повторим по строкам 2 раза по столбцам 3 раза
x = np.array([[1, 2], [3,4]])
y = np.tile(x, (2,3))
print(y)

[[1 2 1 2 1 2]
 [3 4 3 4 3 4]
 [1 2 1 2 1 2]
 [3 4 3 4 3 4]]


# Индексы, срезы, итерации

In [42]:
a = np.arange(10) ** 3
print('a\n', a)
print('a[1]\n', a[1])
print('a[3:7]\n', a[3:7])
a[3:7] = 8
print('a[3:7] = 8\n   ', a)
print('a[::-1]\n   ', a[::-1])
#Невозможно удалить срез элементов
#del a[4:6]
#print('del a[4:6]\n   ', a)
for i in a:
    print('каждый элемент возводим в степень 1/3', i ** (1/3))

a
 [  0   1   8  27  64 125 216 343 512 729]
a[1]
 1
a[3:7]
 [ 27  64 125 216]
a[3:7] = 8
    [  0   1   8   8   8   8   8 343 512 729]
a[::-1]
    [729 512 343   8   8   8   8   8   1   0]
каждый элемент возводим в степень 1/3 0.0
каждый элемент возводим в степень 1/3 1.0
каждый элемент возводим в степень 1/3 2.0
каждый элемент возводим в степень 1/3 2.0
каждый элемент возводим в степень 1/3 2.0
каждый элемент возводим в степень 1/3 2.0
каждый элемент возводим в степень 1/3 2.0
каждый элемент возводим в степень 1/3 6.999999999999999
каждый элемент возводим в степень 1/3 7.999999999999999
каждый элемент возводим в степень 1/3 8.999999999999998


In [55]:
b = np.array([[  0, 1, 2, 3],
              [10, 11, 12, 13],
              [20, 21, 22, 23],
              [30, 31, 32, 33],
              [40, 41, 42, 43]])
print('Вторая строка, третий столбец', b[2,3])  # Вторая строка, третий столбец
print('Вторая строка, третий столбец', b[(2,3)])
print('Вторая строка, третий столбец', b[2][3])  # Можно и так
print('Третий столбец', b[:,2])  # Третий столбец
print('Первые две строки', b[:2])  # Первые две строки
print('Вторая и третья строки', b[1:3, : : ])  # Вторая и третья строки
print('Последняя строка', b[-1])  # Последняя строка. Эквивалентно b[-1,:]
#x[1, 2, ...] эквивалентно x[1, 2, :, :, :]
#x[... , 3] то же самое, что x[:, :, :, :, 3] 
#x[4, ... , 5, :] это x[4, :, :, 5, :]
print('первая строка b[1, ...]\n', b[1, ...])  # то же, что b[1, : , :] или b[1]
print('второй столбец b[... ,2]', b[... ,2])  # то же, что b[: , : ,2]

Вторая строка, третий столбец 23
Вторая строка, третий столбец 23
Вторая строка, третий столбец 23
Третий столбец [ 2 12 22 32 42]
Первые две строки [[ 0  1  2  3]
 [10 11 12 13]]
Вторая и третья строки [[10 11 12 13]
 [20 21 22 23]]
Последняя строка [40 41 42 43]
первая строка b[1, ...]
 [10 11 12 13]
второй столбец b[... ,2] [ 2 12 22 32 42]


# Итерирование

In [59]:
#итерированеи начинается по строкам
print('итерирование построчно\n')
for row in b:
    print(row)
    
#если нужно перебрать поэлементно весь массив, 
#как если бы он был одномерным, 
#для этого можно использовать атрибут flat
print('\nитерирование поэлементно b.flat\n')
for el in b.flat:
    print(el)

итерирование построчно

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]

итерирование поэлементно b.flat

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


# Создание массива той же формы

In [20]:
x = np.array([[1,2],[3,4],[5,6]], dtype=np.float64)
y = np.zeros_like(x)
print('zeros_like(x)\n', y)
z = np.empty_like(x)
print('empty_like(x)\n', z)
w = np.ones_like(x)
print('ones_like(x)\n', w)

zeros_like(x)
 [[0. 0.]
 [0. 0.]
 [0. 0.]]
empty_like(x)
 [[0. 0.]
 [0. 0.]
 [0. 0.]]
ones_like(x)
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [26]:
x = np.array([[1,1], [2,2]])
p = np.full_like(x, 6.2, np.float64)
print('full_like(x, 6.2, np.float64)\n', p)


full_like(x, 6.2, np.float64)
 [[6.2 6.2]
 [6.2 6.2]]


In [29]:
#формируем массив с типом данных - "object"
t = np.array([2.5, 'string', [2,4], {'a': 0, 'b':1}], dtype=object)
print(t)
x = np.empty((2,2), dtype=np.object)
print(x)

[2.5 'string' list([2, 4]) {'a': 0, 'b': 1}]
[[None None]
 [None None]]


In [91]:
#arange создает массив, состоящий из n элементов — от 0 до n — 1
nd6 = np.arange(5)
print(nd6)

[0 1 2 3 4]


In [92]:
#от -3 до 10 с шагом 2
nd7 = np.arange(-3, 10, 2)
print(nd7)

[-3 -1  1  3  5  7  9]


In [93]:
#Функция linspace() (можно использовать вместо arange), 
#которая вместо шага в качестве одного из аргументов принимает число, 
#равное количеству нужных элементов
nd7_= np.linspace(0, 2, 9)  # 9 чисел от 0 до 2 включительно
print('Девять элементов выбранных функцией linspace в диапазоне от 0 до 2: ', nd7_)
#Преобразование типа данных
nd7_= np.linspace(0, 2, 9).astype('int64')
print('Данные преобразованны в другой тип: ', nd7_)

Девять элементов выбранных функцией linspace в диапазоне от 0 до 2:  [0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]
Данные преобразованны в другой тип:  [0 0 0 0 1 1 1 1 2]


In [94]:
#функции примененяются поочередно к каждому элементу многомерного массива
print('np.sin: ', np.sin(nd7))
print('np.cos: ', np.cos(nd7))
print('np.arctan: ', np.arctan(nd7))
print('np.abs: ', np.abs(nd7))
print('np.sign: ', np.sign(nd7))

np.sin:  [-0.14112001 -0.84147098  0.84147098  0.14112001 -0.95892427  0.6569866   0.41211849]
np.cos:  [-0.9899925   0.54030231  0.54030231 -0.9899925   0.28366219  0.75390225 -0.91113026]
np.arctan:  [-1.24904577 -0.78539816  0.78539816  1.24904577  1.37340077  1.42889927  1.46013911]
np.abs:  [3 1 1 3 5 7 9]
np.sign:  [-1 -1  1  1  1  1  1]


# Агрегационные функции

In [33]:
#сгенерируем массив размера 4×4 из нормального распределения
arr1 = np.random.randn(4,4)
print('нормальное распределение arr1: ', arr1)
#сгенерируем массив размера 4×4 из равномерного распределения
arr2 = np.random.rand(4,4)
print('равномерное распределение arr2: ', arr2)

нормальное распределение arr1:  [[-1.02370025 -0.64418404 -1.41875037 -0.28652715]
 [ 1.27297679 -1.19561044  0.11308307 -1.59318959]
 [-1.98562454 -3.35420824  0.59507814  0.40950329]
 [ 0.39668482  0.95767481 -2.14502566  0.72081611]]
равномерное распределение arr2:  [[0.41104924 0.11537719 0.06595501 0.1001126 ]
 [0.93428817 0.65122214 0.18430973 0.6698361 ]
 [0.07565008 0.62356269 0.25629467 0.19657088]
 [0.94575891 0.27138801 0.44098143 0.31097561]]


In [36]:
#Применяем агрегационные функции
#sum() — подсчитывает сумму всех элементов в массиве
#mean() — находим среднее арифметическое
#std() — возвращает значение стандартного отклонения
#var() — возвращает значение дисперсии (разброса) элементов массива
print('sum(arr1): ', np.sum(arr1))
print('sum(arr2): ', np.sum(arr2))
print('mean(arr1): ', np.mean(arr1))
print('mean(arr2): ', np.mean(arr2))
print('std(arr1): ', np.std(arr1))
print('std(arr2): ', np.std(arr2))
print('var(arr1): ', np.var(arr1))
print('var(arr2): ', np.var(arr2))

sum(arr1):  -9.181003247701446
sum(arr2):  6.253332468180036
mean(arr1):  -0.5738127029813404
mean(arr2):  0.3908332792612523
std(arr1):  1.2698706630848695
std(arr2):  0.2839930600953234
var(arr1):  1.612571500963606
var(arr2):  0.08065205818230596


In [104]:
arr1_ = np.array([[1, 20, 3], [4, 5, 6]], dtype='int16')
print('arr1\n', arr1_)
print('min среди всех элементов: ', arr1_.min())
print('max среди всех элементов: ', arr1_.max())
print('max элемент в каждом столбце', arr1_.max(axis=0))
print('max элемент в каждой строке', arr1_.max(axis=1))

arr1
 [[ 1 20  3]
 [ 4  5  6]]
min среди всех элементов:  1
max среди всех элементов:  20
max элемент в каждом столбце [ 4 20  6]
max элемент в каждой строке [20  6]


# Создание массива на основе функции, принимающей индексы (номера элементов)

In [14]:
arr3 = np.fromfunction(lambda i, j: 2*i + j, (3, 4))
print('Создание массива с использованием функции (arr3):\n', arr3)

Создание массива с использованием функции (arr3):
 [[0. 1. 2. 3.]
 [2. 3. 4. 5.]
 [4. 5. 6. 7.]]


In [16]:
#i- индекс строки, j - индекс столбца
def f1(i, j):
    return 3 * i + j
print('Создание массива с использованием функции:\n', np.fromfunction(f1, (3, 4)))


Создание массива с использованием функции:
 [[0. 1. 2. 3.]
 [3. 4. 5. 6.]
 [6. 7. 8. 9.]]


# Печать массивов

In [44]:
print(np.arange(0, 1001, 1))

[   0    1    2    3    4
    5    6    7    8    9
   10   11   12   13   14
   15   16   17   18   19
 ...  981  982  983  984
  985  986  987  988  989
  990  991  992  993  994
  995  996  997  998  999
 1000]


In [45]:
np.set_printoptions(threshold=10)
print(np.arange(0, 20, 1))

[ 0  1  2  3  4  5  6  7
  8  9 10 11 12 13 14 15
 16 17 18 19]


In [46]:
# Использование функции numpy.set_printoptions, чтобы увидеть весь массив
np.set_printoptions(threshold=30)
print('Использование функции numpy.set_printoptions:\n', np.arange(0, 20, 1))

Использование функции numpy.set_printoptions:
 [ 0  1  2  3  4  5  6  7
  8  9 10 11 12 13 14 15
 16 17 18 19]


In [72]:
#Аргументы функции numpy.set_printoptions
'''precision : количество отображаемых цифр после запятой (по умолчанию 8).

threshold : количество элементов в массиве, вызывающее обрезание элементов (по умолчанию 1000).

edgeitems : количество элементов в начале и в конце каждой размерности массива (по умолчанию 3).

linewidth : количество символов в строке, после которых осуществляется перенос (по умолчанию 75).

suppress : если True, не печатает маленькие значения в scientific notation (по умолчанию False).

nanstr : строковое представление NaN (по умолчанию 'nan').

infstr : строковое представление inf (по умолчанию 'inf').

formatter : позволяет более тонко управлять печатью массивов.'''
np.set_printoptions(threshold=30, edgeitems=20, linewidth=260)
print('Использование функции numpy.set_printoptions:\n', np.arange(0, 50, 1))

Использование функции numpy.set_printoptions:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 ... 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


# Базовые операции

In [59]:
#Математические операции над массивами выполняются поэлементно. 
#Создается новый массив, который заполняется результатами действия оператора.
#Массивы должны быть одинаковых размеров.

a = np.array([20, 30, 40, 50])
b = np.arange(4)
print('Поэлементное сложение массивов: ', a + b)
print('Поэлементное вычитание массивов: ', a - b)
print('Поэлементное перемножение массивов: ', a * b)
print('Поэлементное деление массивов:\n', a / b)
print('Поэлементное возведение в степень массивов:\n', a ** b)
print('Поэлементное целочисленное деление массивов:\n', a // b)
print('Поэлементное взятие остатока от деления массивов:\n', a % b)

Поэлементное сложение массивов:  [20 31 42 53]
Поэлементное вычитание массивов:  [20 29 38 47]
Поэлементное перемножение массивов:  [  0  30  80 150]
Поэлементное деление массивов:
 [        inf 30.
 20.         16.66666667]
Поэлементное возведение в степень массивов:
 [     1     30   1600
 125000]
Поэлементное целочисленное деление массивов:
 [ 0 30 20 16]
Поэлементное взятие остатока от деления массивов:
 [0 0 0 2]


C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: RuntimeWarning: divide by zero encountered in true_divide
  # Remove the CWD from sys.path while we load stuff.
C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:12: RuntimeWarning: divide by zero encountered in floor_divide
  if sys.path[0] == '':
C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: RuntimeWarning: divide by zero encountered in remainder
  del sys.path[0]


In [70]:
#Можно производить математические операции между массивом и числом. 
#В этом случае к каждому элементу прибавляется это число.
#Данные операции создают новый массив не меняя старый.
print('a = ', a)
print('a + 1 = ', a + 1)
print('a ** 3 = ', a ** 3)
#Данная операция изменяет старый массив
a -= 1
print('Операция со старым массивом (a -= 1) :', a)

a =  [17 27 37 47]
a + 1 =  [18 28 38 48]
a ** 3 =  [  4913  19683  50653
 103823]
Операция со старым массивом (a -= 1) : [16 26 36 46]


In [82]:
#Фильтрация
a = np.array([5, 0, 20, -13, 25, 4, 30, -1, 40, -7, 50], dtype='int32')
print('a < 35 :', a < 35)
print('Отбираем элементы, которые меньше 10 (a[a < 10]) :\n', a[a < 10])

a < 35 : [ True  True  True  True  True  True  True  True False  True False]
Отбираем элементы, которые меньше 10 (a[a < 10]) :
 [  5   0 -13   4  -1  -7]
