# Numpy

In [13]:
#импорт библиотеки numpy
import numpy as np

In [85]:
#создание массива
nd = np.array([[1, 1, 0], [1, 0, 1]])
print(nd)

[[1 1 0]
 [1 0 1]]


In [3]:
x = np.array([i**2 for i in range(5)])
print(x)

[ 0  1  4  9 16]


# Свойства массива

In [86]:
print('Число измерений массива (размерность,ранг) (nd.ndim): ', nd.ndim)
print('Размеры массива (nd.shape): ', nd.shape)
print('Общее количество всех элементов (nd.size): ', nd.size)
print('Тип элемента в массиве (nd.dtype): ', nd.dtype)

#Указываем тип данных при создании
nd1 = np.array([[1, 1, 0], [1, 0, 1]], dtype=np.float32)
print('type nd1 (nd1.dtype): ', nd1.dtype)

#переопределение типов элементов массива в момент создания
print('Изначальный тип элементов массива: ', ([[1.5, 2, 3], [4, 5, 6]]))
print('', )
nd1_ = np.array([[1.5, 2, 3], [4, 5, 6]], dtype=np.complex)
print('Измененный тип элементов массива nd1 (nd1_): ', nd1_)

print('Pазмер одного элемента массива, указанный в байтах (nd.itemsize): ', nd.itemsize)
print('Буфер, содержащий фактические элементы массива(nd1.data): ', nd1.data)
print('Перевод в список из буфера (nd1.data.tolist)', nd1.data.tolist())

Число измерений массива (размерность,ранг) (nd.ndim):  2
Размеры массива (nd.shape):  (2, 3)
Общее количество всех элементов (nd.size):  6
Тип элемента в массиве (nd.dtype):  int32
type nd1 (nd1.dtype):  float32
Изначальный тип элементов массива:  [[1.5, 2, 3], [4, 5, 6]]

Измененный тип элементов массива nd1 (nd1_):  [[1.5+0.j 2. +0.j 3. +0.j]
 [4. +0.j 5. +0.j 6. +0.j]]
Pазмер одного элемента массива, указанный в байтах (nd.itemsize):  4
Буфер, содержащий фактические элементы массива(nd1.data):  <memory at 0x0000022396D6DEA0>
Перевод в список из буфера (nd1.data.tolist) [[1.0, 1.0, 0.0], [1.0, 0.0, 1.0]]


# Изменение формы массива

In [22]:
a = np.array([[[  0,   1,   2], [ 10,  12,  13]], [[100, 101, 102], [110, 112, 113]]])
print('массив а\n', a)
print('посмотреть форму массива\n', a.shape)
print('получить плоский массив\n', a.ravel())  # Делает массив плоским
a.shape = (6, 2)
print('изменить форму\n', a.shape)  # Изменение формы
print('новый массив\n', a)
print('транспонирование\n', a.transpose() ) # Транспонирование
print('изменить форму a.reshape((3, 4)\n', a.reshape((3, 4)))  # Изменение формы
#reshape изменяет размерность массива, не меняя сами данные
print('reshape изменяет размерность массива, не меняя сами данные: ')
a0 = np.arange(6)
b = np.reshape(a0, (3,2))
print('np.reshape(a0, (3,2))\n', 'b = \n', b)
print('a0 = \n', a0)
b[0,0] = 9
print('Присвоим b[0,0] = 9 ,', '\nb = \n', b)
print('a0 = \n', a0)
a0 = np.reshape(np.arange(6), (2,-1))
print('np.power(a0,2) = \n', np.power(a0,2))
#Порядок элементов в массиве в результате функции ravel() 
#соответствует обычному "C-стилю", то есть, чем правее индекс, тем он "быстрее изменяется": за элементом a[0,0] следует a[0,1]. 
#Если одна форма массива была изменена на другую, массив 
a1=a.reshape((3, 4))
print('a1\n', a1)
print('a1[1]', a1[1])
#в FORTRAN-стиле, в котором быстрее изменяется более левый индекс
a2=a.reshape((3, 4), order='F')
print('a2\n', a2)
print('a2[1]', a2[1])

массив а
 [[[  0   1   2]
  [ 10  12  13]]

 [[100 101 102]
  [110 112 113]]]
посмотреть форму массива
 (2, 2, 3)
получить плоский массив
 [  0   1   2  10  12  13 100 101 102 110 112 113]
изменить форму
 (6, 2)
новый массив
 [[  0   1]
 [  2  10]
 [ 12  13]
 [100 101]
 [102 110]
 [112 113]]
транспонирование
 [[  0   2  12 100 102 112]
 [  1  10  13 101 110 113]]
изменить форму a.reshape((3, 4)
 [[  0   1   2  10]
 [ 12  13 100 101]
 [102 110 112 113]]
reshape изменяет размерность массива, не меняя сами данные: 
np.reshape(a0, (3,2))
 b = 
 [[0 1]
 [2 3]
 [4 5]]
a0 = 
 [0 1 2 3 4 5]
Присвоим b[0,0] = 9 , 
b = 
 [[9 1]
 [2 3]
 [4 5]]
a0 = 
 [9 1 2 3 4 5]
np.power(a0,2) = 
 [[ 0  1  4]
 [ 9 16 25]]
a1
 [[  0   1   2  10]
 [ 12  13 100 101]
 [102 110 112 113]]
a1[1] [ 12  13 100 101]
a2
 [[  0 100   1 101]
 [  2 102  10 110]
 [ 12 112  13 113]]
a2[1] [  2 102  10 110]


In [88]:
#Метод reshape() возвращает ее аргумент с измененной формой, 
#в то время как метод resize() изменяет сам массив
a = np.array([[  0,   1], [  2,  10], [ 12,  13], [100, 101], [102, 110], [112, 113]])
g = a.resize((2, 6))
print('Новый а, после g = a.resize((2, 6)\n', a)
#если один из аргументов задается как -1, 
#то он автоматически рассчитывается в соответствии с остальным
j = a.reshape((4, -1))
print('копия а с 4-мя строками и соответстветствующим количеством столбцов\n', j)

Новый а, после g = a.resize((2, 6)
 [[  0   1   2  10  12  13]
 [100 101 102 110 112 113]]
копия а с 4-мя строками и соответстветствующим количеством столбцов
 [[  0   1   2]
 [ 10  12  13]
 [100 101 102]
 [110 112 113]]


# Объединение массивов

In [ ]:
#Несколько массивов могут быть объединены вместе вдоль разных осей 
#с помощью функций hstack и vstack.

#hstack() объединяет массивы по первым осям, vstack() — по последним

In [3]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print('np.vstack \n', np.vstack((a, b)))
print('np.hstack \n', np.hstack((a, b)))

np.vstack 
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
np.hstack 
 [[1 2 5 6]
 [3 4 7 8]]


In [4]:
#функция column_stack() объединяет одномерные массивы в качестве столбцов 
#двумерного массива
np.column_stack((a, b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [5]:
#для строк имеется функция row_stack()
np.row_stack((a, b))


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [3]:
#соединяем последовательность массивов вдоль произвольной оси
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[10,20,30],[40,50,60], [70,80,90]])
z = np.concatenate([x,y])
print(z)

[[ 1  2  3]
 [ 4  5  6]
 [10 20 30]
 [40 50 60]
 [70 80 90]]


In [5]:
x = np.array([[1,2,3,4],[5,6,7,8]])
y = np.array([[10,20],[30,40]])
z = np.concatenate([x,y], axis=1)
print(z)

[[ 1  2  3  4 10 20]
 [ 5  6  7  8 30 40]]


In [7]:
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[7,8,9]])
z = np.append(x, y, axis=0)
print(z)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Разбиение массива

In [12]:
#Используя hsplit() вы можете разбить массив вдоль горизонтальной оси, 
#указав либо число возвращаемых массивов одинаковой формы, 
#либо номера столбцов, после которых массив разрезается "ножницами"
a = np.arange(12).reshape((2, 6))
print('первоначальный массив  a\n', a)
p = np.hsplit(a, 3)
print('\nмассив, разбитый на 3 части\n')  # Разбить на 3 части
print('часть первая\n', p[0])
print('часть вторая\n', p[1])
print('часть третья\n', p[2])

первоначальный массив  a
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

массив, разбитый на 3 части

часть первая
 [[0 1]
 [6 7]]
часть вторая
 [[2 3]
 [8 9]]
часть третья
 [[ 4  5]
 [10 11]]


In [14]:
n = np.hsplit(a, (3, 4))  # Разрезать a после третьего и четвёртого столбца
print('первая часть\n', n[0])
print('вторая часть\n', n[1])
print('третья часть\n', n[2])

первая часть
 [[0 1 2]
 [6 7 8]]
вторая часть
 [[3]
 [9]]
третья часть
 [[ 4  5]
 [10 11]]


In [17]:
#Функция vsplit() разбивает массив вдоль вертикальной оси, 
m = np.vsplit(a, 2) 
print('первая часть\n', m[0])
print('вторая часть\n', m[1])

первая часть
 [[0 1 2 3 4 5]]
вторая часть
 [[ 6  7  8  9 10 11]]


In [19]:
#а array_split() позволяет указать оси, вдоль которых произойдет разбиение
g = np.array_split(a, 2, axis=0) 
print('первая часть\n', g[0])
print('вторая часть\n', g[1])

первая часть
 [[0 1 2 3 4 5]]
вторая часть
 [[ 6  7  8  9 10 11]]


In [20]:
f = np.array_split(a, 2, axis=1) 
print('первая часть\n', f[0])
print('вторая часть\n', f[1])

первая часть
 [[0 1 2]
 [6 7 8]]
вторая часть
 [[ 3  4  5]
 [ 9 10 11]]


# Представление или поверхностная копия

In [23]:
#Разные объекты массивов могут использовать одни и те же данные. 
#Метод view() создает новый объект массива, 
#являющийся представлением тех же данных.
a = np.array([1,2,3])
c = a.view()
print('"c is a"', c is a)
print('"c.base is a"', c.base is a)  # c это представление данных, принадлежащих a

"c is a" False
"c.base is a" True


In [24]:
print('"c.flags.owndata"', c.flags.owndata)
print('"a.flags.owndata"', a.flags.owndata)

"c.flags.owndata" False
"a.flags.owndata" True


In [27]:
c.shape = (1,3)
print('c.shape', c.shape)  # форма c поменяется
print('a.shape', a.shape)  # форма а не поменяется

c.shape (1, 3)
a.shape (3,)


In [31]:
#данные меняются (в а) после замены элемента в с
c[0, 1] = 9999
print('a', a, 'c', c)

a [   1 9999    3] c [[   1 9999    3]]


In [34]:
#Срез массива это представление
a = np.array([[1,2,3], [4,5,6]])
s = a[:,1:3]
s[:] = 10
print(s)

[[10 10]
 [10 10]]


# Глубокая копия

In [37]:
#Метод copy() создаст настоящую копию массива и его данных
d = a.copy()  # создается новый объект массива с новыми данными
print(d is a)
print(d.base is a)  # d не имеет ничего общего с а
d[0, 0] = 9999 #после изменения элемента в d - в а ничего не меняется
print(a)

False
False
[[ 1 10 10]
 [ 4 10 10]]


# Ссылка на объект в памяти

In [17]:
a = np.array([[1,2],[3,4]])
b = a
b[0,0] = 6
print('a = \n', a)
print('b = \n', b)

a = 
 [[6 2]
 [3 4]]
b = 
 [[6 2]
 [3 4]]


# Инициализация значениями по умолчанию

Можно создать массивы и инициализировать нулями или единицами. Для этого в NumPy существуют две говорящие сами за себя функции zeros() и ones()

In [87]:
nd2 = np.zeros((3, 3))
print(nd2)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [88]:
nd3 = np.ones((3, 3))
print(nd3)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [89]:
#создание единичной матрицы
nd4 = np.eye(3)
print(nd4)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [90]:
#создание матрицы с мусорными значениями
nd5 = np.empty((4,4))
print(nd5)

[[6.23042070e-307 4.67296746e-307 1.69121096e-306 9.34609111e-307]
 [1.11256817e-306 1.06811422e-306 1.42417221e-306 1.11260619e-306]
 [8.90094053e-307 1.86919378e-306 1.06809792e-306 1.37962456e-306]
 [1.69111861e-306 1.78020169e-306 1.37961777e-306 7.56599807e-307]]


In [7]:
#создание матрицы 3 на 2 и заполнение ее элементами -2 с типом int32
x = np.full((3, 2), -2, np.int32)
print(x)

[[-2 -2]
 [-2 -2]
 [-2 -2]]


# Создание массива путем повторения элементов

In [8]:
x = np.array([[1,2,3],[4,5,6]])
y = np.repeat(x,2)
print(y)

[1 1 2 2 3 3 4 4 5 5 6 6]


In [9]:
y = np.repeat(x, 2, axis=0)
print(y)

[[1 2 3]
 [1 2 3]
 [4 5 6]
 [4 5 6]]


In [10]:
y = np.repeat(x, 2, axis=1)
print(y)

[[1 1 2 2 3 3]
 [4 4 5 5 6 6]]


In [13]:
y = np.repeat(x, [2, 0, 5], axis = 1)
print(y)

[[1 1 3 3 3 3 3]
 [4 4 6 6 6 6 6]]


In [15]:
#повторим по строкам 2 раза по столбцам 3 раза
x = np.array([[1, 2], [3,4]])
y = np.tile(x, (2,3))
print(y)

[[1 2 1 2 1 2]
 [3 4 3 4 3 4]
 [1 2 1 2 1 2]
 [3 4 3 4 3 4]]


# Индексы, срезы, итерации

In [42]:
a = np.arange(10) ** 3
print('a\n', a)
print('a[1]\n', a[1])
print('a[3:7]\n', a[3:7])
a[3:7] = 8
print('a[3:7] = 8\n   ', a)
print('a[::-1]\n   ', a[::-1])
#Невозможно удалить срез элементов
#del a[4:6]
#print('del a[4:6]\n   ', a)
for i in a:
    print('каждый элемент возводим в степень 1/3', i ** (1/3))

a
 [  0   1   8  27  64 125 216 343 512 729]
a[1]
 1
a[3:7]
 [ 27  64 125 216]
a[3:7] = 8
    [  0   1   8   8   8   8   8 343 512 729]
a[::-1]
    [729 512 343   8   8   8   8   8   1   0]
каждый элемент возводим в степень 1/3 0.0
каждый элемент возводим в степень 1/3 1.0
каждый элемент возводим в степень 1/3 2.0
каждый элемент возводим в степень 1/3 2.0
каждый элемент возводим в степень 1/3 2.0
каждый элемент возводим в степень 1/3 2.0
каждый элемент возводим в степень 1/3 2.0
каждый элемент возводим в степень 1/3 6.999999999999999
каждый элемент возводим в степень 1/3 7.999999999999999
каждый элемент возводим в степень 1/3 8.999999999999998


In [55]:
b = np.array([[  0, 1, 2, 3],
              [10, 11, 12, 13],
              [20, 21, 22, 23],
              [30, 31, 32, 33],
              [40, 41, 42, 43]])
print('Вторая строка, третий столбец', b[2,3])  # Вторая строка, третий столбец
print('Вторая строка, третий столбец', b[(2,3)])
print('Вторая строка, третий столбец', b[2][3])  # Можно и так
print('Третий столбец', b[:,2])  # Третий столбец
print('Первые две строки', b[:2])  # Первые две строки
print('Вторая и третья строки', b[1:3, : : ])  # Вторая и третья строки
print('Последняя строка', b[-1])  # Последняя строка. Эквивалентно b[-1,:]
#x[1, 2, ...] эквивалентно x[1, 2, :, :, :]
#x[... , 3] то же самое, что x[:, :, :, :, 3] 
#x[4, ... , 5, :] это x[4, :, :, 5, :]
print('первая строка b[1, ...]\n', b[1, ...])  # то же, что b[1, : , :] или b[1]
print('второй столбец b[... ,2]', b[... ,2])  # то же, что b[: , : ,2]

Вторая строка, третий столбец 23
Вторая строка, третий столбец 23
Вторая строка, третий столбец 23
Третий столбец [ 2 12 22 32 42]
Первые две строки [[ 0  1  2  3]
 [10 11 12 13]]
Вторая и третья строки [[10 11 12 13]
 [20 21 22 23]]
Последняя строка [40 41 42 43]
первая строка b[1, ...]
 [10 11 12 13]
второй столбец b[... ,2] [ 2 12 22 32 42]


In [31]:
#делаем срез из массива
y = x[2:4, 3:6]
print(y)

[[0.95942292 0.24611286 0.97164448]
 [0.1196962  0.19440163 0.06352755]]


In [32]:
y = x[[2,3,1], [0,3,5]]
print(y)

[0.16488805 0.1196962  0.04687856]


In [33]:
y = x[[2,0,3], :] [:, [-2,1]]
print(y)

[[0.36046883 0.24315335]
 [0.15791204 0.99406377]
 [0.96334803 0.97537189]]


In [37]:
x = np.array([[-1,2,4], [2,-3,1], [2,4,0], [-5,4,3], [3,1,1], [2,0,-4]])
row_sums = x.sum(axis=1)
print(row_sums)
y = x[row_sums % 2 == 0, :]
print(y)


[ 5  0  6  2  5 -2]
[[ 2 -3  1]
 [ 2  4  0]
 [-5  4  3]
 [ 2  0 -4]]


# Итерирование

In [27]:
#при использовании "for ... in" итерация выполняется только по первой размерности

#итерирование начинается по строкам
print('итерирование построчно\n')
for row in b:
    print(row)
    
#если нужно перебрать поэлементно весь массив, 
#как если бы он был одномерным, 
#для этого можно использовать атрибут flat
print('\nитерирование поэлементно b.flat\n')
for el in b.flat:
    print(el)
    
#чтобы сделать итерацию по всем элементам используем ravel 
print('\nитерирование поэлементно np.ravel(b)\n')
for i in np.ravel(b): 
    print('Element', i)
#flatten возвращает копию. 
#ravel возвращает представление оригинального массива

итерирование построчно

[9 1]
[2 3]
[4 5]

итерирование поэлементно b.flat

9
1
2
3
4
5

итерирование поэлементно np.ravel(b)

Element 9
Element 1
Element 2
Element 3
Element 4
Element 5


# Создание массива той же формы

In [20]:
x = np.array([[1,2],[3,4],[5,6]], dtype=np.float64)
y = np.zeros_like(x)
print('zeros_like(x)\n', y)
z = np.empty_like(x)
print('empty_like(x)\n', z)
w = np.ones_like(x)
print('ones_like(x)\n', w)

zeros_like(x)
 [[0. 0.]
 [0. 0.]
 [0. 0.]]
empty_like(x)
 [[0. 0.]
 [0. 0.]
 [0. 0.]]
ones_like(x)
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [26]:
x = np.array([[1,1], [2,2]])
p = np.full_like(x, 6.2, np.float64)
print('full_like(x, 6.2, np.float64)\n', p)


full_like(x, 6.2, np.float64)
 [[6.2 6.2]
 [6.2 6.2]]


In [29]:
#формируем массив с типом данных - "object"
t = np.array([2.5, 'string', [2,4], {'a': 0, 'b':1}], dtype=object)
print(t)
x = np.empty((2,2), dtype=np.object)
print(x)

[2.5 'string' list([2, 4]) {'a': 0, 'b': 1}]
[[None None]
 [None None]]


In [91]:
#arange создает массив, состоящий из n элементов — от 0 до n — 1
nd6 = np.arange(5)
print(nd6)

[0 1 2 3 4]


In [92]:
#от -3 до 10 с шагом 2
nd7 = np.arange(-3, 10, 2)
print(nd7)

[-3 -1  1  3  5  7  9]


In [93]:
#Функция linspace() (можно использовать вместо arange), 
#которая вместо шага в качестве одного из аргументов принимает число, 
#равное количеству нужных элементов
nd7_= np.linspace(0, 2, 9)  # 9 чисел от 0 до 2 включительно
print('Девять элементов выбранных функцией linspace в диапазоне от 0 до 2: ', nd7_)
#Преобразование типа данных
nd7_= np.linspace(0, 2, 9).astype('int64')
print('Данные преобразованны в другой тип: ', nd7_)

Девять элементов выбранных функцией linspace в диапазоне от 0 до 2:  [0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]
Данные преобразованны в другой тип:  [0 0 0 0 1 1 1 1 2]


In [94]:
#функции примененяются поочередно к каждому элементу многомерного массива
print('np.sin: ', np.sin(nd7))
print('np.cos: ', np.cos(nd7))
print('np.arctan: ', np.arctan(nd7))
print('np.abs: ', np.abs(nd7))
print('np.sign: ', np.sign(nd7))

np.sin:  [-0.14112001 -0.84147098  0.84147098  0.14112001 -0.95892427  0.6569866   0.41211849]
np.cos:  [-0.9899925   0.54030231  0.54030231 -0.9899925   0.28366219  0.75390225 -0.91113026]
np.arctan:  [-1.24904577 -0.78539816  0.78539816  1.24904577  1.37340077  1.42889927  1.46013911]
np.abs:  [3 1 1 3 5 7 9]
np.sign:  [-1 -1  1  1  1  1  1]


# random

In [7]:
import random
print('использование random.random\n', np.array([random.random() for i in range(10)]))
print('использование random.randint\n', np.array([random.randint(2,20) for i in range(10)]))

использование random.random
 [0.99334987 0.37162527 0.5252237  0.99780718 0.02361839 0.21879408
 0.94088405 0.67866132 0.46777055 0.07645201]
использование random.randint
 [10  4  9 10 20  5 18 14 14  5]


In [12]:
import numpy as np  # Импортировать numpy и писать np.random
print(' "np.random" ', np.random)
import numpy.random as rand  # Можно и присвоить отдельное имя. Вопрос вкуса
print(' "rand" ', rand)

 "np.random"  <module 'numpy.random' from 'C:\\Users\\user\\Anaconda3\\lib\\site-packages\\numpy\\random\\__init__.py'>
 "rand"  <module 'numpy.random' from 'C:\\Users\\user\\Anaconda3\\lib\\site-packages\\numpy\\random\\__init__.py'>


# Создание массивов с использованием random и др

In [19]:
#Самый простой способ задать массив со случайными элементами - использовать функцию sample 
#(или random, или random_sample, или ranf - это всё одна и та же функция).
print('np.random.sample()', np.random.sample())
print('np.random.sample(1)', np.random.sample(1))
print('np.random.sample(3)', np.random.sample(3))
print('np.random.sample((4,5)\n', np.random.sample((4,5)))
#Без аргументов возвращает просто число в промежутке [0, 1), с одним целым числом - одномерный 
#массив, с кортежем - массив с размерами, указанными в кортеже (все числа - из промежутка [0, 1))

np.random.sample() 0.8687158884888498
np.random.sample(1) [0.49027137]
np.random.sample(3) [0.46922293 0.75684649 0.30930943]
np.random.sample((4,5)
 [[0.58815378 0.81053814 0.37050376 0.63188258 0.72315358]
 [0.87084598 0.54158302 0.37441092 0.78426813 0.93435703]
 [0.95683574 0.61552116 0.84738879 0.51868688 0.56818797]
 [0.72906412 0.67274675 0.05565758 0.03480726 0.38808328]]


In [23]:
#С помощью функции randint или random_integers можно создать массив из целых чисел. 
#Аргументы: low, high, size: от какого, до какого числа (randint не включает 
#в себя это число, а random_integers включает), и size - размеры массива.
print('np.random.randint(0, 3, 10)', np.random.randint(0, 3, 10))
print('np.random.random_integers(0, 3, 10)', np.random.random_integers(0, 3, 10))
print('np.random.randint(0, 3, (2, 10))\n', np.random.randint(0, 3, (2, 10)))

np.random.randint(0, 3, 10) [1 0 0 0 1 2 1 0 2 1]
np.random.random_integers(0, 3, 10) [2 2 2 0 2 1 3 3 2 0]
np.random.randint(0, 3, (2, 10))
 [[0 2 0 2 2 2 0 2 1 1]
 [1 2 1 1 0 2 2 1 1 0]]


C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: DeprecationWarning: This function is deprecated. Please call randint(0, 3 + 1) instead
  """


In [26]:
#Также можно генерировать числа согласно различным распределениям (Гаусса, Парето и другие). 
#Распределение с помощь функции uniform
print('np.random.uniform(2, 8, (2, 5))\n', np.random.uniform(2, 8, (2, 5)))

np.random.uniform(2, 8, (2, 5))
 [[5.01631538 2.87507769 6.51937602 3.85930457 2.98897365]
 [2.75222134 4.34037968 6.0100418  3.80511568 3.44275423]]


# Выбор и перемешивание

In [30]:
#Перемешать NumPy массив можно с помощью функции shuffle
a = np.arange(10)
print('до перемешивания', a)
np.random.shuffle(a)
print('после перемешивания shuffle', a)

до перемешивания [0 1 2 3 4 5 6 7 8 9]
после перемешивания shuffle [0 6 7 1 5 3 9 2 4 8]


In [35]:
#Также можно перемешать массив с помощью функции permutation (она, 
#в отличие от shuffle, возвращает перемешанный массив). Также она, 
#вызванная с одним аргументом (целым числом), возвращает перемешанную 
#последовательность от 0 до N.
print('permutation создает перемешнную копию', np.random.permutation(10))

g = np.arange(7)
print('g', g)
print('permutation создает перемешнную копию g', np.random.permutation(g))
r = np.array([9, 8, 7, 6, 5, 4])
print('r', r)
print('permutation создает перемешнную копию r', np.random.permutation(r))

permutation создает перемешнную копию [9 5 0 1 8 7 3 2 4 6]
g [0 1 2 3 4 5 6]
permutation создает перемешнную копию g [3 5 2 0 4 1 6]
r [9 8 7 6 5 4]
permutation создает перемешнную копию r [8 7 9 5 6 4]


In [38]:
#Сделать случайную выборку из массива можно с помощью функции choice. 
np.random.choice(a, size=None, replace=True, p=None)
#a : одномерный массив или число
#size : размерности массива
#replace : если True, то одно значение может выбираться более одного раза

#p : вероятности. Это означает, что элементы можно выбирать с неравными 
#вероятностями. Если не заданы, используется равномерное распределение
a = np.arange(10)
print('a', a)
h = np.random.choice(a, 10, p=[0.5, 0.25, 0.25, 0, 0, 0, 0, 0, 0, 0])
print('использование random.choice', h)


a [0 1 2 3 4 5 6 7 8 9]
использование random.choice [0 0 2 1 0 0 1 0 2 1]


# Инициализация генератора случайных чисел

In [43]:
#seed(число) - инициализация генератора
np.random.seed(1000)
print('seed=1000', np.random.random(10))
np.random.seed(100)
print('seed=100', np.random.random(10))
np.random.seed(1000)
print('seed=1000', np.random.random(10))

seed=1000 [0.65358959 0.11500694 0.95028286 0.4821914  0.87247454 0.21233268
 0.04070962 0.39719446 0.2331322  0.84174072]
seed=100 [0.54340494 0.27836939 0.42451759 0.84477613 0.00471886 0.12156912
 0.67074908 0.82585276 0.13670659 0.57509333]
seed=1000 [0.65358959 0.11500694 0.95028286 0.4821914  0.87247454 0.21233268
 0.04070962 0.39719446 0.2331322  0.84174072]


In [45]:
#get_state и set_state - возвращают и устанавливают состояние генератора
np.random.seed(1000)
#get_state возвращает кортеж, представляющий внутреннее состояние генератора
state = np.random.get_state()
print('state\n', state)
np.random.random(10)

state
 ('MT19937', array([      1000, 4252021385, 1724402292,  571538732,   73690720,
       4283493349, 2222270404, 2464917285,  427676011, 1101193792,
       2887716015, 3670250828, 1664757559, 1538426459, 1540041616,
       1315948868, 1639142729,  962342265, 1073918415, 1993958489,
        417312460, 1549738641,  217559782, 2562763477, 3209786859,
       2560374278, 4171592622, 3387504732,  382145687, 3400593072,
       2993747901,  895481210, 2542805826, 3850053729, 3839975628,
       3814914254, 4140621317, 2614021763,  916554251,  782053758,
         99808478, 3086444991, 2623397051,   20321832, 3880396276,
        743647648, 2708868174, 1178306091, 4084099266, 1776655702,
       2854986373, 3806486134, 2567889245, 2534654384, 2438049136,
       3777589297,  734135794, 1515772595, 1156942452, 3240836452,
       2075941087, 3002064339,  856579251, 3777715678, 3630321009,
        811110459, 1304263305, 3423346667, 3174285004, 1982367115,
        741968312, 2708393439, 3656220025, 

array([0.65358959, 0.11500694, 0.95028286, 0.4821914 , 0.87247454,
       0.21233268, 0.04070962, 0.39719446, 0.2331322 , 0.84174072])

# Агрегационные функции

In [33]:
#сгенерируем массив размера 4×4 из нормального распределения
arr1 = np.random.randn(4,4)
print('нормальное распределение arr1: ', arr1)
#сгенерируем массив размера 4×4 из равномерного распределения
arr2 = np.random.rand(4,4)
print('равномерное распределение arr2: ', arr2)

нормальное распределение arr1:  [[-1.02370025 -0.64418404 -1.41875037 -0.28652715]
 [ 1.27297679 -1.19561044  0.11308307 -1.59318959]
 [-1.98562454 -3.35420824  0.59507814  0.40950329]
 [ 0.39668482  0.95767481 -2.14502566  0.72081611]]
равномерное распределение arr2:  [[0.41104924 0.11537719 0.06595501 0.1001126 ]
 [0.93428817 0.65122214 0.18430973 0.6698361 ]
 [0.07565008 0.62356269 0.25629467 0.19657088]
 [0.94575891 0.27138801 0.44098143 0.31097561]]


In [36]:
#Применяем агрегационные функции
#sum() — подсчитывает сумму всех элементов в массиве
#mean() — находим среднее арифметическое
#std() — возвращает значение стандартного отклонения
#var() — возвращает значение дисперсии (разброса) элементов массива
print('sum(arr1): ', np.sum(arr1))
print('sum(arr2): ', np.sum(arr2))
print('mean(arr1): ', np.mean(arr1))
print('mean(arr2): ', np.mean(arr2))
print('std(arr1): ', np.std(arr1))
print('std(arr2): ', np.std(arr2))
print('var(arr1): ', np.var(arr1))
print('var(arr2): ', np.var(arr2))

sum(arr1):  -9.181003247701446
sum(arr2):  6.253332468180036
mean(arr1):  -0.5738127029813404
mean(arr2):  0.3908332792612523
std(arr1):  1.2698706630848695
std(arr2):  0.2839930600953234
var(arr1):  1.612571500963606
var(arr2):  0.08065205818230596


In [104]:
arr1_ = np.array([[1, 20, 3], [4, 5, 6]], dtype='int16')
print('arr1\n', arr1_)
print('min среди всех элементов: ', arr1_.min())
print('max среди всех элементов: ', arr1_.max())
print('max элемент в каждом столбце', arr1_.max(axis=0))
print('max элемент в каждой строке', arr1_.max(axis=1))

arr1
 [[ 1 20  3]
 [ 4  5  6]]
min среди всех элементов:  1
max среди всех элементов:  20
max элемент в каждом столбце [ 4 20  6]
max элемент в каждой строке [20  6]


# Индексация

In [36]:
a = np.arange(6)*2
i = np.array([1,3,5,2])
print('a[i] = \n', a[i])
i = np.array([[1,3],[5,2]])
print('a[i] = \n', a[i])
#использование bool для индексации/отбора
print('a ', a)
print('a>4 ', a>4)
print('a[a>4] ', a[a>4])

a[i] = 
 [ 2  6 10  4]
a[i] = 
 [[ 2  6]
 [10  4]]
a  [ 0  2  4  6  8 10]
a>4  [False False False  True  True  True]
a[a>4]  [ 6  8 10]


# Создание массива на основе функции, принимающей индексы (номера элементов)

In [14]:
arr3 = np.fromfunction(lambda i, j: 2*i + j, (3, 4))
print('Создание массива с использованием функции (arr3):\n', arr3)

Создание массива с использованием функции (arr3):
 [[0. 1. 2. 3.]
 [2. 3. 4. 5.]
 [4. 5. 6. 7.]]


In [16]:
#i- индекс строки, j - индекс столбца
def f1(i, j):
    return 3 * i + j
print('Создание массива с использованием функции:\n', np.fromfunction(f1, (3, 4)))


Создание массива с использованием функции:
 [[0. 1. 2. 3.]
 [3. 4. 5. 6.]
 [6. 7. 8. 9.]]


In [15]:
a = np.fromfunction(lambda i,j: i==j, (3,3))
print(a)

[[ True False False]
 [False  True False]
 [False False  True]]


# Печать массивов

In [44]:
print(np.arange(0, 1001, 1))

[   0    1    2    3    4
    5    6    7    8    9
   10   11   12   13   14
   15   16   17   18   19
 ...  981  982  983  984
  985  986  987  988  989
  990  991  992  993  994
  995  996  997  998  999
 1000]


In [45]:
np.set_printoptions(threshold=10)
print(np.arange(0, 20, 1))

[ 0  1  2  3  4  5  6  7
  8  9 10 11 12 13 14 15
 16 17 18 19]


In [46]:
# Использование функции numpy.set_printoptions, чтобы увидеть весь массив
np.set_printoptions(threshold=30)
print('Использование функции numpy.set_printoptions:\n', np.arange(0, 20, 1))

Использование функции numpy.set_printoptions:
 [ 0  1  2  3  4  5  6  7
  8  9 10 11 12 13 14 15
 16 17 18 19]


In [72]:
#Аргументы функции numpy.set_printoptions
'''precision : количество отображаемых цифр после запятой (по умолчанию 8).

threshold : количество элементов в массиве, вызывающее обрезание элементов (по умолчанию 1000).

edgeitems : количество элементов в начале и в конце каждой размерности массива (по умолчанию 3).

linewidth : количество символов в строке, после которых осуществляется перенос (по умолчанию 75).

suppress : если True, не печатает маленькие значения в scientific notation (по умолчанию False).

nanstr : строковое представление NaN (по умолчанию 'nan').

infstr : строковое представление inf (по умолчанию 'inf').

formatter : позволяет более тонко управлять печатью массивов.'''
np.set_printoptions(threshold=30, edgeitems=20, linewidth=260)
print('Использование функции numpy.set_printoptions:\n', np.arange(0, 50, 1))

Использование функции numpy.set_printoptions:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 ... 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


# Базовые операции

In [59]:
#Математические операции над массивами выполняются поэлементно. 
#Создается новый массив, который заполняется результатами действия оператора.
#Массивы должны быть одинаковых размеров.

a = np.array([20, 30, 40, 50])
b = np.arange(4)
print('Поэлементное сложение массивов: ', a + b)
print('Поэлементное вычитание массивов: ', a - b)
print('Поэлементное перемножение массивов: ', a * b)
print('Поэлементное деление массивов:\n', a / b)
print('Поэлементное возведение в степень массивов:\n', a ** b)
print('Поэлементное целочисленное деление массивов:\n', a // b)
print('Поэлементное взятие остатока от деления массивов:\n', a % b)

Поэлементное сложение массивов:  [20 31 42 53]
Поэлементное вычитание массивов:  [20 29 38 47]
Поэлементное перемножение массивов:  [  0  30  80 150]
Поэлементное деление массивов:
 [        inf 30.
 20.         16.66666667]
Поэлементное возведение в степень массивов:
 [     1     30   1600
 125000]
Поэлементное целочисленное деление массивов:
 [ 0 30 20 16]
Поэлементное взятие остатока от деления массивов:
 [0 0 0 2]


C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: RuntimeWarning: divide by zero encountered in true_divide
  # Remove the CWD from sys.path while we load stuff.
C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:12: RuntimeWarning: divide by zero encountered in floor_divide
  if sys.path[0] == '':
C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: RuntimeWarning: divide by zero encountered in remainder
  del sys.path[0]


In [70]:
#Можно производить математические операции между массивом и числом. 
#В этом случае к каждому элементу прибавляется это число.
#Данные операции создают новый массив не меняя старый.
print('a = ', a)
print('a + 1 = ', a + 1)
print('a ** 3 = ', a ** 3)
#Данная операция изменяет старый массив
a -= 1
print('Операция со старым массивом (a -= 1) :', a)

a =  [17 27 37 47]
a + 1 =  [18 28 38 48]
a ** 3 =  [  4913  19683  50653
 103823]
Операция со старым массивом (a -= 1) : [16 26 36 46]


In [82]:
#Фильтрация
a = np.array([5, 0, 20, -13, 25, 4, 30, -1, 40, -7, 50], dtype='int32')
print('a < 35 :', a < 35)
print('Отбираем элементы, которые меньше 10 (a[a < 10]) :\n', a[a < 10])

a < 35 : [ True  True  True  True  True  True  True  True False  True False]
Отбираем элементы, которые меньше 10 (a[a < 10]) :
 [  5   0 -13   4  -1  -7]


#  NumPy

In [42]:
#Перемножение матриц
a = np.array([[2.3, 4.5, -3.1], [1.2, 3.2, 4.0]])
b = np.array([[2.1, -4.6, 0.5, 2.2], [-1.2, -3.0, 1.7, 3.2], [3.1, 2.6, 1.1, 2.3]])
c = a.dot(b)
print(c)

[[-10.18 -32.14   5.39  12.33]
 [ 11.08  -4.72  10.44  22.08]]


In [61]:
#модуль numpy.linalg, позволяет делать многие операции из линейной алгебры
a = np.array([[1,2,3], [4,5,6], [7,8,10]])
print('a\n', a)
print('a.T\n', a.T)
#Возведение в степень
# linalg.matrix_power(M, n) - возводит матрицу в степень n
print('возведение в степень 2 матрицы a\n', np.linalg.matrix_power(a, 2))
print('1*1+2*4+3*7=30')
#Разложения
#linalg.cholesky(a) - разложение Холецкого
#Разложе́ние Холе́цкого — представление симметричной положительно-определённой 
#матрицы  A в виде A=LL^T
#где L — нижняя треугольная матрица со строго положительными элементами на диагонали
c = np.array([[6,-2], [-2,1]])
#linalg.det(a) - определитель
d = np.linalg.det(c)
print('d', d)
print('разложение Холецкого\n', np.linalg.cholesky(c))

a
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]
a.T
 [[ 1  4  7]
 [ 2  5  8]
 [ 3  6 10]]
возведение в степень 2 матрицы a
 [[ 30  36  45]
 [ 66  81 102]
 [109 134 169]]
1*1+2*4+3*7=30
d 2.0
разложение Холецкого
 [[ 2.44948974  0.        ]
 [-0.81649658  0.57735027]]


In [66]:
#linalg.qr(a[, mode]) - QR разложение
#QR - разложение матрицы — представление матрицы в виде произведения унитарной 
#(или ортогональной матрицы) и верхнетреугольной матрицы. QR-разложение является 
#основой одного из методов поиска собственных векторов и чисел матрицы QR алгоритма
# A = Q * R, Q - унитарная мартица n на n, R - верхнетреугольная матрица n на n
l = np.array([[6,-2], [-2,1]])
print('QR - разложение матрицы\n', np.linalg.qr(l))


#linalg.svd(a[, full_matrices, compute_uv]) - сингулярное разложение
#Сингуля́рное разложе́ние — определённого типа разложение прямоугольной матрицы. 
#Имеющее широкое применение, в силу своей наглядной геометрической интерпретации, 
#при решении многих прикладных задач. 
z = np.array([[6,5], [-2,1]])
print('svd разложение - возвращает поцентру матрицу сингулярных чисел, слева и справа - унитарные вектора \n', np.linalg.svd(z))

QR - разложение матрицы
 (array([[-0.9486833 ,  0.31622777],
       [ 0.31622777,  0.9486833 ]]), array([[-6.32455532,  2.21359436],
       [ 0.        ,  0.31622777]]))
svd разложение - возвращает поцентру матрицу сингулярных чисел, слева и справа - унитарные вектора 
 (array([[-0.99250756,  0.12218326],
       [ 0.12218326,  0.99250756]]), array([7.86522342, 2.03427152]), array([[-0.78820544, -0.61541221],
       [-0.61541221,  0.78820544]]))


In [71]:
#linalg.eig(a) - собственные значения и собственные векторы
print('собственные значения и собственные векторы\n', np.linalg.eig(a))
print('собственные значения \n', np.linalg.eig(a)[0])
print('собственные вектора\n', np.linalg.eig(a)[1])

собственные значения и собственные векторы
 (array([16.70749332, -0.90574018,  0.19824686]), array([[-0.22351336, -0.86584578,  0.27829649],
       [-0.50394563,  0.0856512 , -0.8318468 ],
       [-0.83431444,  0.4929249 ,  0.48018951]]))
собственные значения 
 [16.70749332 -0.90574018  0.19824686]
собственные вектора
 [[-0.22351336 -0.86584578  0.27829649]
 [-0.50394563  0.0856512  -0.8318468 ]
 [-0.83431444  0.4929249   0.48018951]]


In [73]:
#linalg.norm(x[, ord, axis]) - норма вектора или оператора
print('норма вектора или оператора\n', np.linalg.norm(a, 1))

норма вектора или оператора
 19.0


In [75]:
#linalg.cond(x[, p]) - число обусловленности
print('число обусловленности\n', np.linalg.cond(a))

число обусловленности
 88.4482799206987


In [76]:
#linalg.slogdet(a) - знак и логарифм определителя 
#(для избежания переполнения, если сам определитель очень маленький)
print('знак и логарифм определителя \n', np.linalg.slogdet(a))

знак и логарифм определителя 
 (-1.0, 1.09861228866811)


In [79]:
#linalg.solve(a, b) - решает систему линейных уравнений Ax = b
A = np.array([[1, 1], [2, 3]])
b = np.array([10, -10])
print('решение систем линейных уравнений,x1, x2 \n', np.linalg.solve(A, b))

#linalg.tensorsolve(a, b[, axes]) - решает тензорную систему линейных уравнений Ax = b

решение систем линейных уравнений,x1, x2 
 [ 40. -30.]


In [84]:
#linalg.lstsq(a, b[, rcond]) - метод наименьших квадратов
print('метод наименьших квадратов, x1, x2 \n', np.linalg.lstsq(A, b))

A = np.array([[1, 1], [2, 2]])
b = np.array([10, -10])
print('метод наименьших квадратов, x1, x2 \n', np.linalg.lstsq(A, b))

#linalg.inv(a) - обратная матрица
print('a\n', a)
print('обратная матрица \n', np.linalg.inv(a))

метод наименьших квадратов, x1, x2 
 (array([-1., -1.]), array([], dtype=float64), 1, array([3.16227766e+00, 8.22677308e-17]))
метод наименьших квадратов, x1, x2 
 (array([-1., -1.]), array([], dtype=float64), 1, array([3.16227766e+00, 8.22677308e-17]))
a
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]
обратная матрица 
 [[-0.66666667 -1.33333333  1.        ]
 [-0.66666667  3.66666667 -2.        ]
 [ 1.         -2.          1.        ]]


C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  
C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  


# Протокол ufunc 

In [41]:
#Протокол ufunc применяет функцию к каждому элементу массива(произвольной вложенности)
x = np.pi * np.arange(0,2,0.25)
y = np.sin(x)+1
print('x', x)
print('y', y)

x [0.         0.78539816 1.57079633 2.35619449 3.14159265 3.92699082
 4.71238898 5.49778714]
y [1.         1.70710678 2.         1.70710678 1.         0.29289322
 0.         0.29289322]


# Использование masked arrays

In [43]:
import numpy.ma as ma
x = np.array([1.0, 3.2, -2.1, 4.3, 5.4])
xm = ma.masked_array(x, [0, 0, 1, 0, 0])
repr(xm)

'masked_array(data=[1.0, 3.2, --, 4.3, 5.4],\n             mask=[False, False,  True, False, False],\n       fill_value=1e+20)'

In [44]:
x = np.array([[i+j for j in range(i, i+5)]
             for i in range(5)])
xm = ma.masked_inside(x,4,6)
print(x)
print(xm)

[[ 0  1  2  3  4]
 [ 2  3  4  5  6]
 [ 4  5  6  7  8]
 [ 6  7  8  9 10]
 [ 8  9 10 11 12]]
[[0 1 2 3 --]
 [2 3 -- -- --]
 [-- -- -- 7 8]
 [-- 7 8 9 10]
 [8 9 10 11 12]]


In [ ]:
#Функции
#masked_equal(x,v)
#masked_greater(x,v)
#masked_greater_equal(x,v)
#masked_insidel(x,v1, v2)
#masked_invalid(x)
#masked_less(x,v)
#masked_not_equal(x,v)
#masked_outside(x,v1,v2)
#masked_where(condition,v)

# Сохранение и загрузка

In [9]:
#сохранение
x = np.random.rand(200,300)
np.savetxt('array_x.txt', x)

In [13]:
#загрузка
x1 = np.loadtxt('array_x.txt')
print(x[0, 0], x1[0, 0])

0.3097003557257807 0.3097003557257807


In [19]:
# csv формат
m, n = 10, 5
x = np.random.rand(m,n)
columns = ','.join(['Column {}'.format(str(i+1)) for i in range(n)])
np.savetxt('array_x.csv', x, delimiter=',', header=columns, comments='')

In [20]:
#бинарный формат
x = np.random.rand(200, 220)
np.save('array_x.npy', x)

In [21]:
x = np.random.rand(200, 220)
y = np.random.rand(20)
z = np.random.rand(10,5,7)
np.savez('arrays_xyz.npz', xfile=x, yfile=y, zfile=z)

In [22]:
#сохраняем сжатый файл
np.savez_compressed('arrays_xyz_c.npz', xfile=x, yfile=y, zfile=z)

In [25]:
x = np.load('array_x.npy') 
x[0][0]

0.1326137996135549

In [30]:
arrays = np.load('arrays_xyz.npz')
x, y, z =[arrays[name] for name in ['xfile', 'yfile', 'zfile']]
print(list(arrays.keys()))
print(x[0,0])

['xfile', 'yfile', 'zfile']
0.6527349674288406


# Символьные вычисления

In [7]:
from sympy import *
import numpy as np
init_printing(use_latex=True)
r, theta = symbols('r, theta')
x = r * cos(theta)
y = r * sin(theta)
print('x = ', x, 'y = ', y)

x =  r*cos(theta) y =  r*sin(theta)


In [12]:
polar_to_rectangular = lambdify((r, theta), (x,y), modules='numpy')
r_values = np.array([2, 1.5, -3])
theta_values = np.array([np.pi/4, np.pi/2, -np.pi])
print('Полярные координаты: \n', 'r_values =', r_values, 'theta_values =', theta_values)
xvalues, yvalues = polar_to_rectangular(r_values, theta_values)
print('Декартовые координаты: \n', 'xvalues = ', xvalues, 'yvalues = ', yvalues)

Полярные координаты: 
 r_values = [ 2.   1.5 -3. ] theta_values = [ 0.78539816  1.57079633 -3.14159265]
Декартовые координаты: 
 xvalues =  [1.41421356e+00 9.18485099e-17 3.00000000e+00] yvalues =  [1.41421356e+00 1.50000000e+00 3.67394040e-16]
