# Numpy

In [84]:
#импорт библиотеки numpy
import numpy as np

In [85]:
#создание массива
nd = np.array([[1, 1, 0], [1, 0, 1]])
print(nd)

[[1 1 0]
 [1 0 1]]


# Свойства массива

In [86]:
print('Число измерений массива (размерность,ранг) (nd.ndim): ', nd.ndim)
print('Размеры массива (nd.shape): ', nd.shape)
print('Общее количество всех элементов (nd.size): ', nd.size)
print('Тип элемента в массиве (nd.dtype): ', nd.dtype)

#Указываем тип данных при создании
nd1 = np.array([[1, 1, 0], [1, 0, 1]], dtype=np.float32)
print('type nd1 (nd1.dtype): ', nd1.dtype)

#переопределение типов элементов массива в момент создания
print('Изначальный тип элементов массива: ', ([[1.5, 2, 3], [4, 5, 6]]))
print('', )
nd1_ = np.array([[1.5, 2, 3], [4, 5, 6]], dtype=np.complex)
print('Измененный тип элементов массива nd1 (nd1_): ', nd1_)

print('Pазмер одного элемента массива, указанный в байтах (nd.itemsize): ', nd.itemsize)
print('Буфер, содержащий фактические элементы массива(nd1.data): ', nd1.data)
print('Перевод в список из буфера (nd1.data.tolist)', nd1.data.tolist())

Число измерений массива (размерность,ранг) (nd.ndim):  2
Размеры массива (nd.shape):  (2, 3)
Общее количество всех элементов (nd.size):  6
Тип элемента в массиве (nd.dtype):  int32
type nd1 (nd1.dtype):  float32
Изначальный тип элементов массива:  [[1.5, 2, 3], [4, 5, 6]]

Измененный тип элементов массива nd1 (nd1_):  [[1.5+0.j 2. +0.j 3. +0.j]
 [4. +0.j 5. +0.j 6. +0.j]]
Pазмер одного элемента массива, указанный в байтах (nd.itemsize):  4
Буфер, содержащий фактические элементы массива(nd1.data):  <memory at 0x0000022396D6DEA0>
Перевод в список из буфера (nd1.data.tolist) [[1.0, 1.0, 0.0], [1.0, 0.0, 1.0]]


# Инициализация значениями по умолчанию

Можно создать массивы и инициализировать нулями или единицами. Для этого в NumPy существуют две говорящие сами за себя функции zeros() и ones()

In [87]:
nd2 = np.zeros((3, 3))
print(nd2)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [88]:
nd3 = np.ones((3, 3))
print(nd3)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [89]:
#создание единичной матрицы
nd4 = np.eye(3)
print(nd4)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [90]:
#создание матрицы с мусорными значениями
nd5 = np.empty((4,4))
print(nd5)

[[6.23042070e-307 4.67296746e-307 1.69121096e-306 9.34609111e-307]
 [1.11256817e-306 1.06811422e-306 1.42417221e-306 1.11260619e-306]
 [8.90094053e-307 1.86919378e-306 1.06809792e-306 1.37962456e-306]
 [1.69111861e-306 1.78020169e-306 1.37961777e-306 7.56599807e-307]]


# Математические функции

In [91]:
#arange создает массив, состоящий из n элементов — от 0 до n — 1
nd6 = np.arange(5)
print(nd6)

[0 1 2 3 4]


In [92]:
#от -3 до 10 с шагом 2
nd7 = np.arange(-3, 10, 2)
print(nd7)

[-3 -1  1  3  5  7  9]


In [93]:
#Функция linspace() (можно использовать вместо arange), 
#которая вместо шага в качестве одного из аргументов принимает число, 
#равное количеству нужных элементов
nd7_= np.linspace(0, 2, 9)  # 9 чисел от 0 до 2 включительно
print('Девять элементов выбранных функцией linspace в диапазоне от 0 до 2: ', nd7_)
#Преобразование типа данных
nd7_= np.linspace(0, 2, 9).astype('int64')
print('Данные преобразованны в другой тип: ', nd7_)

Девять элементов выбранных функцией linspace в диапазоне от 0 до 2:  [0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]
Данные преобразованны в другой тип:  [0 0 0 0 1 1 1 1 2]


In [94]:
#функции примененяются поочередно к каждому элементу многомерного массива
print('np.sin: ', np.sin(nd7))
print('np.cos: ', np.cos(nd7))
print('np.arctan: ', np.arctan(nd7))
print('np.abs: ', np.abs(nd7))
print('np.sign: ', np.sign(nd7))

np.sin:  [-0.14112001 -0.84147098  0.84147098  0.14112001 -0.95892427  0.6569866   0.41211849]
np.cos:  [-0.9899925   0.54030231  0.54030231 -0.9899925   0.28366219  0.75390225 -0.91113026]
np.arctan:  [-1.24904577 -0.78539816  0.78539816  1.24904577  1.37340077  1.42889927  1.46013911]
np.abs:  [3 1 1 3 5 7 9]
np.sign:  [-1 -1  1  1  1  1  1]


# Агрегационные функции

In [33]:
#сгенерируем массив размера 4×4 из нормального распределения
arr1 = np.random.randn(4,4)
print('нормальное распределение arr1: ', arr1)
#сгенерируем массив размера 4×4 из равномерного распределения
arr2 = np.random.rand(4,4)
print('равномерное распределение arr2: ', arr2)

нормальное распределение arr1:  [[-1.02370025 -0.64418404 -1.41875037 -0.28652715]
 [ 1.27297679 -1.19561044  0.11308307 -1.59318959]
 [-1.98562454 -3.35420824  0.59507814  0.40950329]
 [ 0.39668482  0.95767481 -2.14502566  0.72081611]]
равномерное распределение arr2:  [[0.41104924 0.11537719 0.06595501 0.1001126 ]
 [0.93428817 0.65122214 0.18430973 0.6698361 ]
 [0.07565008 0.62356269 0.25629467 0.19657088]
 [0.94575891 0.27138801 0.44098143 0.31097561]]


In [36]:
#Применяем агрегационные функции
#sum() — подсчитывает сумму всех элементов в массиве
#mean() — находим среднее арифметическое
#std() — возвращает значение стандартного отклонения
#var() — возвращает значение дисперсии (разброса) элементов массива
print('sum(arr1): ', np.sum(arr1))
print('sum(arr2): ', np.sum(arr2))
print('mean(arr1): ', np.mean(arr1))
print('mean(arr2): ', np.mean(arr2))
print('std(arr1): ', np.std(arr1))
print('std(arr2): ', np.std(arr2))
print('var(arr1): ', np.var(arr1))
print('var(arr2): ', np.var(arr2))

sum(arr1):  -9.181003247701446
sum(arr2):  6.253332468180036
mean(arr1):  -0.5738127029813404
mean(arr2):  0.3908332792612523
std(arr1):  1.2698706630848695
std(arr2):  0.2839930600953234
var(arr1):  1.612571500963606
var(arr2):  0.08065205818230596


In [104]:
arr1_ = np.array([[1, 20, 3], [4, 5, 6]], dtype='int16')
print('arr1\n', arr1_)
print('min среди всех элементов: ', arr1_.min())
print('max среди всех элементов: ', arr1_.max())
print('max элемент в каждом столбце', arr1_.max(axis=0))
print('max элемент в каждой строке', arr1_.max(axis=1))

arr1
 [[ 1 20  3]
 [ 4  5  6]]
min среди всех элементов:  1
max среди всех элементов:  20
max элемент в каждом столбце [ 4 20  6]
max элемент в каждой строке [20  6]


# Создание массива на основе функции, принимающей индексы (номера элементов)

In [14]:
arr3 = np.fromfunction(lambda i, j: 2*i + j, (3, 4))
print('Создание массива с использованием функции (arr3):\n', arr3)

Создание массива с использованием функции (arr3):
 [[0. 1. 2. 3.]
 [2. 3. 4. 5.]
 [4. 5. 6. 7.]]


In [16]:
#i- индекс строки, j - индекс столбца
def f1(i, j):
    return 3 * i + j
print('Создание массива с использованием функции:\n', np.fromfunction(f1, (3, 4)))


Создание массива с использованием функции:
 [[0. 1. 2. 3.]
 [3. 4. 5. 6.]
 [6. 7. 8. 9.]]


# Печать массивов

In [44]:
print(np.arange(0, 1001, 1))

[   0    1    2    3    4
    5    6    7    8    9
   10   11   12   13   14
   15   16   17   18   19
 ...  981  982  983  984
  985  986  987  988  989
  990  991  992  993  994
  995  996  997  998  999
 1000]


In [45]:
np.set_printoptions(threshold=10)
print(np.arange(0, 20, 1))

[ 0  1  2  3  4  5  6  7
  8  9 10 11 12 13 14 15
 16 17 18 19]


In [46]:
# Использование функции numpy.set_printoptions, чтобы увидеть весь массив
np.set_printoptions(threshold=30)
print('Использование функции numpy.set_printoptions:\n', np.arange(0, 20, 1))

Использование функции numpy.set_printoptions:
 [ 0  1  2  3  4  5  6  7
  8  9 10 11 12 13 14 15
 16 17 18 19]


In [72]:
#Аргументы функции numpy.set_printoptions
'''precision : количество отображаемых цифр после запятой (по умолчанию 8).

threshold : количество элементов в массиве, вызывающее обрезание элементов (по умолчанию 1000).

edgeitems : количество элементов в начале и в конце каждой размерности массива (по умолчанию 3).

linewidth : количество символов в строке, после которых осуществляется перенос (по умолчанию 75).

suppress : если True, не печатает маленькие значения в scientific notation (по умолчанию False).

nanstr : строковое представление NaN (по умолчанию 'nan').

infstr : строковое представление inf (по умолчанию 'inf').

formatter : позволяет более тонко управлять печатью массивов.'''
np.set_printoptions(threshold=30, edgeitems=20, linewidth=260)
print('Использование функции numpy.set_printoptions:\n', np.arange(0, 50, 1))

Использование функции numpy.set_printoptions:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 ... 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


# Базовые операции

In [59]:
#Математические операции над массивами выполняются поэлементно. 
#Создается новый массив, который заполняется результатами действия оператора.
#Массивы должны быть одинаковых размеров.

a = np.array([20, 30, 40, 50])
b = np.arange(4)
print('Поэлементное сложение массивов: ', a + b)
print('Поэлементное вычитание массивов: ', a - b)
print('Поэлементное перемножение массивов: ', a * b)
print('Поэлементное деление массивов:\n', a / b)
print('Поэлементное возведение в степень массивов:\n', a ** b)
print('Поэлементное целочисленное деление массивов:\n', a // b)
print('Поэлементное взятие остатока от деления массивов:\n', a % b)

Поэлементное сложение массивов:  [20 31 42 53]
Поэлементное вычитание массивов:  [20 29 38 47]
Поэлементное перемножение массивов:  [  0  30  80 150]
Поэлементное деление массивов:
 [        inf 30.
 20.         16.66666667]
Поэлементное возведение в степень массивов:
 [     1     30   1600
 125000]
Поэлементное целочисленное деление массивов:
 [ 0 30 20 16]
Поэлементное взятие остатока от деления массивов:
 [0 0 0 2]


C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: RuntimeWarning: divide by zero encountered in true_divide
  # Remove the CWD from sys.path while we load stuff.
C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:12: RuntimeWarning: divide by zero encountered in floor_divide
  if sys.path[0] == '':
C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: RuntimeWarning: divide by zero encountered in remainder
  del sys.path[0]


In [70]:
#Можно производить математические операции между массивом и числом. 
#В этом случае к каждому элементу прибавляется это число.
#Данные операции создают новый массив не меняя старый.
print('a = ', a)
print('a + 1 = ', a + 1)
print('a ** 3 = ', a ** 3)
#Данная операция изменяет старый массив
a -= 1
print('Операция со старым массивом (a -= 1) :', a)

a =  [17 27 37 47]
a + 1 =  [18 28 38 48]
a ** 3 =  [  4913  19683  50653
 103823]
Операция со старым массивом (a -= 1) : [16 26 36 46]


In [82]:
#Фильтрация
a = np.array([5, 0, 20, -13, 25, 4, 30, -1, 40, -7, 50], dtype='int32')
print('a < 35 :', a < 35)
print('Отбираем элементы, которые меньше 10 (a[a < 10]) :\n', a[a < 10])

a < 35 : [ True  True  True  True  True  True  True  True False  True False]
Отбираем элементы, которые меньше 10 (a[a < 10]) :
 [  5   0 -13   4  -1  -7]
