# Numpy

In [1]:
#импорт библиотеки numpy
import numpy as np

In [3]:
#создание массива
nd = np.array([[1, 1, 0], [1, 0, 1]])
print(nd)

[[1 1 0]
 [1 0 1]]


# Свойства массива

In [11]:
print('Число измерений массива (размерность,ранг) (nd.ndim): ', nd.ndim)
print('Размеры массива (nd.shape): ', nd.shape)
print('Общее количество всех элементов (nd.size): ', nd.size)
print('Тип элемента в массиве (nd.dtype): ', nd.dtype)
#Указываем тип данных при создании
nd1 = np.array([[1, 1, 0], [1, 0, 1]], dtype=np.float32)
print('type nd1 (nd1.dtype): ', nd1.dtype)
print('Pазмер одного элемента массива, указанный в байтах (nd.itemsize): ', nd.itemsize)

Число измерений массива (размерность,ранг) (nd.ndim):  2
Размеры массива (nd.shape):  (2, 3)
Общее количество всех элементов (nd.size):  6
Тип элемента в массиве (nd.dtype):  int32
type nd1 (nd1.dtype):  float32
Pазмер одного элемента массива, указанный в байтах (nd.itemsize):  4


# Инициализация значениями по умолчанию

Можно создать массивы и инициализировать нулями или единицами. Для этого в NumPy существуют две говорящие сами за себя функции zeros() и ones()

In [13]:
nd2 = np.zeros((3, 3))
print(nd2)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [15]:
nd3 = np.ones((3, 3))
print(nd3)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [16]:
#создание единичной матрицы
nd4 = np.eye(3)
print(nd4)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [24]:
#создание матрицы с мусорными значениями
nd5 = np.empty((4,4))
print(nd5)

[[6.23042070e-307 4.67296746e-307 1.69121096e-306 9.34609111e-307]
 [1.11256817e-306 1.06811422e-306 1.42417221e-306 1.11260619e-306]
 [8.90094053e-307 1.86919378e-306 1.06809792e-306 1.37962456e-306]
 [1.69111861e-306 1.78020169e-306 1.37961777e-306 7.56599807e-307]]


# Математические функции

In [25]:
#arange создает массив, состоящий из n элементов — от 0 до n — 1
nd6 = np.arange(5)
print(nd6)

[0 1 2 3 4]


In [27]:
#от -3 до 10 с шагом 2
nd7 = np.arange(-3, 10, 2)
print(nd7)

[-3 -1  1  3  5  7  9]


In [29]:
#функции примененяются поочередно к каждому элементу многомерного массива
print('np.sin: ', np.sin(nd7))
print('np.cos: ', np.cos(nd7))
print('np.abs: ', np.abs(nd7))
print('np.sign: ', np.sign(nd7))

np.sin:  [-0.14112001 -0.84147098  0.84147098  0.14112001 -0.95892427  0.6569866
  0.41211849]
np.cos:  [-0.9899925   0.54030231  0.54030231 -0.9899925   0.28366219  0.75390225
 -0.91113026]
np.abs:  [3 1 1 3 5 7 9]
np.sign:  [-1 -1  1  1  1  1  1]


# Агрегационные функции

In [33]:
#сгенерируем массив размера 4×4 из нормального распределения
arr1 = np.random.randn(4,4)
print('нормальное распределение arr1: ', arr1)
#сгенерируем массив размера 4×4 из равномерного распределения
arr2 = np.random.rand(4,4)
print('равномерное распределение arr2: ', arr2)

нормальное распределение arr1:  [[-1.02370025 -0.64418404 -1.41875037 -0.28652715]
 [ 1.27297679 -1.19561044  0.11308307 -1.59318959]
 [-1.98562454 -3.35420824  0.59507814  0.40950329]
 [ 0.39668482  0.95767481 -2.14502566  0.72081611]]
равномерное распределение arr2:  [[0.41104924 0.11537719 0.06595501 0.1001126 ]
 [0.93428817 0.65122214 0.18430973 0.6698361 ]
 [0.07565008 0.62356269 0.25629467 0.19657088]
 [0.94575891 0.27138801 0.44098143 0.31097561]]


In [36]:
#Применяем агрегационные функции
#sum() — подсчитывает сумму всех элементов в массиве
#mean() — находим среднее арифметическое
#std() — возвращает значение стандартного отклонения
#var() — возвращает значение дисперсии (разброса) элементов массива
print('sum(arr1): ', np.sum(arr1))
print('sum(arr2): ', np.sum(arr2))
print('mean(arr1): ', np.mean(arr1))
print('mean(arr2): ', np.mean(arr2))
print('std(arr1): ', np.std(arr1))
print('std(arr2): ', np.std(arr2))
print('var(arr1): ', np.var(arr1))
print('var(arr2): ', np.var(arr2))

sum(arr1):  -9.181003247701446
sum(arr2):  6.253332468180036
mean(arr1):  -0.5738127029813404
mean(arr2):  0.3908332792612523
std(arr1):  1.2698706630848695
std(arr2):  0.2839930600953234
var(arr1):  1.612571500963606
var(arr2):  0.08065205818230596
